spring:
  devtools:
    add-properties: false
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off

  # Configuracoes do datasource e Postgres e cache:
  # Hibernate ddl auto (create, create-drop, validate, update)
  # spring.jpa.hibernate.naming.physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${conefer.datasource.url}
    username: ${conefer.datasource.username}
    datasource:
      hikari:
        maximum-pool-size: 20
  cache:
    jcache:
      config : classpath:ehcache.xml
  sql:
    init:
      platform: postgres


########### MULTIPART (MultipartProperties)
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

### Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: versao_database
    schemas: public

# Configuracoes de log:
logging:
  level:
    root: error
    org:
      hibernate: error
    springframework:
      web: error
    br:
      edu:
        ifg:
          manutencao:
            coneferserver: error
  pattern:
    console: "%clr(%d{dd-MM-yyyy E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"

### Properties do sistema
conefer:
  basePackageEnum: "br.edu.ifg.manutencao.coneferserver.entity.enum"
